## YAML Template.
---
version: "0.12 (beta)"
plugins:
    - plugin1:
        - path: ""
        - activo: true
    - plugin2:
        - path: ""
        - activo: true
# 
# Longitud de los botones que muestran los bloques de procesos.
# Menu 'Configuracion Principal/Valores referentes a bloques de procesos'
#
btn_longitud: 20
#
# Cantidad de menus desplegables del menu principal, comenzando en 0.
#
cant_menu: 3
